# Generated by Django 4.2.11 on 2024-03-12 08:21

import ckeditor
import cloudinary
from django import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lesson", name="content", field=ckeditor.fields.RichTextField(),
        ),
        migrations.AddField(
            model_name="lesson",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to="courses.tag"
            ),
        ),
    ]
